name: Discourse Category Jumbotron

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    uses: discourse/.github/.github/workflows/discourse-theme.yml@v1
    with:
      core_ref: v3.5.0
